### ISSUE TITLE
audit and finalize decision on supported versions of dotnet CLR

### ISSUE THREAD

**Issue by cprice404** [momentohq/client-sdk-dotnet#140]
1. Try to decide if we can get away with saying just dotnet 6+.
2. Failing that, let’s call out the reasons why (e.g. framework foo only supports vX, or there is evidence that lots of customers still use vX, or we know that we have a customer who needs vX.  We should sync with Erika on this later, when she is settled.)
3. If we do have to support additional versions it really looked to me like there is only one other one we should consider.  This is partially based on the fact that when you go through the “new project” dialog in visual studio it only gives you two choices.
4. If we do have to support additional versions then let’s do some quick scouting on what tools we need in order to do a test matrix.

**Comment by cprice404** [comment]
outcome of this ticket should just be a proposal for now: what versions to support, what tool to use if we need a matrix.  Let's try to timebox it to a day or if possible.

**Comment by malandis** [comment]
We are currently targeting the framework [netstandard2.1](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1). Note that this is not compatible with .NET Framework. Microsoft recommends targeting netstandard2.0 to retain backwards compatibility with .NET Framework versions 4.6.1+. This gives us access to modern APIs but allows us to support customers with older codebases.

I did a quick test to see how much work is involved to pivot to netstandard2.0 and it is minimal. Thus I recommend switching to netstandard2.0. So we can re-evaluate at a future date, we can track the end-user's .NET runtime in a gRPC header.
