### ISSUE TITLE
request command options object base class for c# sdk

### ISSUE THREAD

**Issue by cprice404** [momentohq/client-sdk-dotnet#145]
Immediate goal for this is just to make sure we understand the impact on the GET/SET APIs for GA.

If we are going to add a builder / base class for the ADS commands, it feels like the GET/SETs would be a little incongruous without them, and that it would probably be a backward-incompatible change to try to switch to them later.  So we need to try to make the call on whether we want to do this, and if so, define the minimum builder interface for GET/SET.  We can late-bind any decisions that are ADS-specific after GA.

**Comment by malandis** [comment]
Conclusion: a command options class is not necessary.

Key points:
- Other clients (eg StackExchange.Redis) use command options to handle command concurrency and cluster options. We have no need for that.

- Cross cutting options in our SDK are limited to TTL. Each `set` command requires a TTL. Data structures also require a `refreshTtl` option, again too few to necessitate a new builder.

- A request builder would help when there is a combinatorial number of overloads for a command. As an example consider a `Dictionary` where the `dictionaryName` could be `bytes` or `string`, and same goes for the `field` and `value`. There would be eight overloads. In this case a request builder would cut the number of functions to 1. Other clients (eg StackExchange.Redis) solve this by abstracting the key and value type to a union/oneof type. That said, clear overloads (eg 8 in the case of dictionary) may be preferable to an end-user, though inconvenient to us as developers. At some point we may consider a union/oneof type to abstract these details.
