### ISSUE TITLE
re-enable warning for missing documentation & fill in missing documentation

### ISSUE THREAD

**Issue by cprice404** [momentohq/client-sdk-dotnet#223]
We do not need to spend time on this for internal classes.  So for anything that is defined in the `Internal` directory, we can just use a compiler directive to disable warnings for those files.  TODO: @malandis add the magical incantation to the ticket.

**Comment by malandis** [comment]
To disable warnings in a whole file, add this to the top of the file:

`#pragma warning disable CS1591`

Note you can also use this to disable the warning in a particular region of a file as well as follows:

```csharp

// code here; subject documentation warnings

#pragma warning disable CS1591
// more code here; documentation warnings will be suppressed
#pragma warning restore CS1591```
