### ISSUE TITLE
implement ellery's suggestions about using time-based constructs for loadgen, etc.

### ISSUE THREAD

**Issue by cprice404** [momentohq/client-sdk-dotnet#229]
Make the load-gen example match the Python and Javascript examples.

- [x] logLevel
- [x] printStatsEveryNRequests -> showStatsInterval
  - [x] Takes a TimeSpan.
- [x]  totalNumberOfOperationsToExecute -> howLongToRun (?)
  - [x] Takes a TimeSpan.
- [x] Display maxRequestsPerSecond, numberOfConcurrentRequests, and howLongToRun to the user before running.

I skipped requestTimeout, the example uses the pre-built Laptop config.

These are very desirable UX improvements because with the current setup, if the user changes `maxRequestsPerSecond` or `numberOfConcurrentRequests`, it will have a big impact on how often (in wall clock time) the stats are printed, as well as how long the program will run for.  That's not intuitive for users.

**Comment by schwern** [comment]
@cprice404 @eaddingtonwhite  What were the suggestions?

**Comment by cprice404** [comment]
@schwern sorry, I will update the description of this ticket now (but it was basically what I already captured in your other ticket).

**Comment by cprice404** [comment]
@schwern updated description, hopefully it's useful now :)

**Comment by schwern** [comment]
I also made sure the stats print when the run finishes, just in case totalMs is not a multiple of printStatsEveryNMs.
