### ISSUE TITLE
finalize the timeout, retry and concurrent request settings on the pre-built configs

### ISSUE THREAD

**Issue by cprice404** [momentohq/client-sdk-dotnet#234]

**Comment by poppoerika** [comment]
First, we will have a meeting with Ellery to discuss the topic further.

**Comment by cprice404** [comment]
Notes from call with Ellery:

There are three settings we need to finalize for each config: max concurrent requests, # of retries, and timeout.

For max concurrent requests we will have Erika experiment with the load generator in laptop/ec2 environments and validate the numbers that I came up with in my experiments.

For retries, we agreed that since our initial retry strategy will just be a naive, immediate, fixed-count retry, that 3 is a reasonable number for all the configs.  This is based on the fact that in testing we are seeing that 1 retry is almost always sufficient, and capping at 3 reduces the likelihood of thundering herd issues.

For timeouts, the straw-man proposals are:
* Laptop: at least 5 seconds, maybe even 15 or 30.  Action items are to research what the AWS defaults are (for smart configs and for DDB), and to run a load gen from a laptop to whatever region we have a cell in that has the worst latency from us.
* InRegion.LowLatency - WAG is 500ms.  Action items are to research AWS defaults and do some loadgen runs from an ec2 node with the value set to 500ms and make sure everything is sane.
* InRegion.Default/Throughput - WAG is 2s.  Action items are to research AWS defaults and do some loadgen runs from ec2.

AWS smart configs reference is here: https://docs.aws.amazon.com/sdkref/latest/guide/feature-smart-config-defaults.html
DDB tuning information here: https://aws.amazon.com/blogs/database/tuning-aws-java-sdk-http-request-settings-for-latency-aware-amazon-dynamodb-applications/

**Comment by cprice404** [comment]
@poppoerika do you have the throughput numbers handy?  Would it be easy to add them to the bullets above?

**Comment by cprice404** [comment]
Let's go with these numbers:
Laptop: timeout: 15s, max concurrency: 100, 3 retries
InRegion.Default: 1100ms, max concurrency: 200, 3 retries
InRegion.LowLatency: 500ms, max concurrency: 20, 3 retries
