### ISSUE TITLE
check for lambda timeout issue

### ISSUE THREAD

**Issue by cprice404** [momentohq/client-sdk-dotnet#335]
In [this ticket](https://github.com/momentohq/client-sdk-javascript/issues/113) we diagnosed an issue where a global variable holding a cache client in the JS SDK was getting corrupted after being idle for longer than the AWS NLB timeout.

We need to be on the lookout for this in all languages that users are likely to use for Lambda development; I'll add that to standards and practices docs as part of https://github.com/momentohq/standards-and-practices/issues/36 .

But for now we should test this in the .NET SDK because we know users are writing Lambdas with it.

[SST docs state that you can use SST to write C# lambdas](https://docs.sst.dev/what-is-sst#functions), so hopefully we can set up pretty much the same test environment that we were using for typescript.

**Comment by poppoerika** [comment]
To invoke a Lambda function via SST, .NET Core 3.1 is required, but my laptop's architecture is arm64 and .NET Core 3.1 is only availabe for x64.
Therefore, no checking for timeout was done vis SST.

Using[ Amazon Lambda Tool for .NET](https://github.com/aws/aws-extensions-for-dotnet-cli#aws-lambda-amazonlambdatools), I deployed a function in [this branch](https://github.com/poppoerika/sst/tree/dotnet-lambda-connection-timeout) and the below is my observation:
- Invoked the function, which resulted in creating a new SimpleCacheClient and succeeding set/get operations.
- Waited for 6 minutes (this exceeds AWS NLB's idle connection timeout of 350 seconds) and invoked the function, no new SimpleCacheClient was created but still set/get operations succeeded (as Chris mentioned the global SimpleCacheClient variable seemed to be reused in this invocation).
- Waited for another 7 minutes and invoked the function, a new SimpleCacheClient was created (as Chris mentioned probably a new Docker container was created to load/run the function so the global SimpleCacheClient variable was removed.)

**Comment by cprice404** [comment]
@poppoerika that sounds perfect.

Did you just invoke it once after each of those wait periods?  Or did you invoke it several times?

**Comment by poppoerika** [comment]
@cprice404 
I invoked a few times after each wait periods. But I didn't see any errors.

**Comment by cprice404** [comment]
perfect, that sounds good then.  We can close this out.
