### ISSUE TITLE
re-order truncate arguments vs collectionttl

### ISSUE THREAD

**Issue by cprice404** [momentohq/client-sdk-dotnet#364]
in the node.js sdk, we had the collection ttl argument ordered before the truncate one.  feedback was that people would use truncate more often, so we want it to appear before collection ttl in the list.

also would be gtk if there are ways to leverage keyword args for passing in the optional arguments.

**Comment by malandis** [comment]
1.The .NET client has always had the truncate option before the TTL :-)
2. .NET also supports keyword arguments. The syntax for this is `argname: value`, eg:

```csharp
client.ListConcatenateFront(ttl: ttl, truncateBackToSize: 50, cacheName: "hello world", values: values)
```
