### ISSUE TITLE
spot check the names of the various value accessors

### ISSUE THREAD

**Issue by cprice404** [momentohq/client-sdk-dotnet#366]
in the node.js SDK, we had some value accessors that were named things like `valueDictionaryStringString`, but the JS data types that they were actually returning were `Map<string, string>` or `Record<string, string>`.  If we are naming these accessors after the types they are returning, we should use the names that make sense for the language.

Spot check the names in .NET for this before we release.

**Comment by malandis** [comment]
1. :green_heart: List -- the .NET canonical list type is `List` (`IList`)
2. :green_heart: Dictionary -- the .NET canonical map type is `Dictionary` (`IDictionary`)
3. :green_heart: Set -- the .NET canonical set type is `Set` (`ISet`)
